@echo off

echo "Press any key to start purge"
pause

echo "Cleaning Unity folders and files"
rmdir /Q /S Build
rmdir /Q /S Builds
rmdir /Q /S Library
rmdir /Q /S LocalCache
rmdir /Q /S Localcache
rmdir /Q /S Obj
rmdir /Q /S Temp
rmdir /Q /S UnityGenerated
rmdir /Q /S Logs
rmdir /Q /S MemoryCaptures
rmdir /Q /S build
rmdir /Q /S builds
rmdir /Q /S library
rmdir /Q /S localCache
rmdir /Q /S localcache
rmdir /Q /S obj
rmdir /Q /S temp
rmdir /Q /S unityGenerated
rmdir /Q /S logs
rmdir /Q /S memoryCaptures

echo "Cleaning Visual Studio cache directory"
rmdir /Q /S .vs

echo "Cleaning Gradle cache directory"
rmdir /Q /S .gradle

echo "Cleaning Autogenerated VS/MD/Consulo files"
rmdir /Q /S ExportedObj
rmdir /Q /S exportedObj
rmdir /Q /S .consulo
del /S *.csproj
del /S *.unityproj
del /S *.sln
del /S *.suo
del /S *.svd
del /S *.tmp
del /S *.user
del /S *.userprefs
del /S *.pidb
del /S *.booproj
del /S *.pdb
del /S *.mdb
del /S *.opendb
del /S *.VC.db

echo "Cleaning Unity3D generated meta files"
del /S *.pidb.meta
del /S *.pdb.meta
del /S *.mdb.meta

echo "Cleaning Unity3D crash reports file"
del /S sysinfo.txt

echo "Cleaning Build files"
del /S *.apk
del /S *.unitypackage

echo "Cleaning Crashlytics generated file"
del /S crashlytics-build.properties

echo "Cleaning System Generated Files"
del /S .DS_Store
del /S .DS_Store?
del /S ._*
del /S .Spotlight-V100
del /S .Trashes
del /S Icon?
del /S ehthumbs.db
del /S Thumbs.db

echo "Deletion Complete"
pause
exit

:extras_dat_my_small_brain_cannot_comprehend
rmdir /Q /S "assets/AssetStoreTools*"
rmdir /Q /S "Assets/AssetStoreTools*"

echo "Cleaning Autogenerated Jetbrains Rider plugin"
rmdir /Q /S "Assets/Plugins/Editor/JetBrains*"
rmdir /Q /S "assets/Plugins/Editor/JetBrains*"

echo "Cleaning Blender Backup Files"
del /S *.blend*
